name: hrs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pyyaml
  - pandas
  - protobuf
  - flask=3.1.2
  - gunicorn=23.0.0
  - python-dotenv=1.2.1
  - pyarrow
  - pip
  - pip:
    - openai==2.9.0
    - google-generativeai==0.8.5
    - chromadb==1.3.5
    - sentence-transformers==5.1.2
